export const pairs =  [
	{ value: "Gold%2FUSD", label: "XAUUSD", symbol: "OANDA:XAUUSD" },
	{ value: "Silver%2FUSD", label: "XAGUSD", symbol: "OANDA:XAGUSD" },
	{ value: "BTC%2FUSD", label: "BTCUSD", symbol: "OANDA:BTCUSD" },
	{ value: "DJ30", label: "US30", symbol: "OANDA:US30" },
	{ value: "NAS100", label: "NAS100", symbol: "OANDA:NAS100" },
	{ value: "SP500", label: "SPX500", symbol: "OANDA:SPX500" },
	{ value: "EUR%2FUSD", label: "EURUSD", symbol: "OANDA:EURUSD" },
	{ value: "GBP%2FUSD", label: "GBPUSD", symbol: "OANDA:GBPUSD" },
	{ value: "AUD%2FUSD", label: "AUDUSD", symbol: "OANDA:AUDUSD" },
	{ value: "NZD%2FUSD", label: "NZDUSD", symbol: "OANDA:NZDUSD" },
	{ value: "USD%2FJPY", label: "USDJPY", symbol: "OANDA:USDJPY" },
	{ value: "USD%2FCAD", label: "USDCAD", symbol: "OANDA:USDCAD" },
	{ value: "USD%2FCHF", label: "USDCHF", symbol: "OANDA:USDCHF" },
	{ value: "GBP%2FJPY", label: "GBPJPY", symbol: "OANDA:GBPJPY" },
	{ value: "GBP%2FCAD", label: "GBPCAD", symbol: "OANDA:GBPCAD" },
	{ value: "EUR%2FCAD", label: "EURCAD", symbol: "OANDA:EURCAD" },
];
