export const pairs = [
	{ value: "EUR%2FUSD", label: "EURUSD", symbol: "OANDA:EURUSD" },
	{ value: "GBP%2FUSD", label: "GBPUSD", symbol: "OANDA:GBPUSD" },
	{ value: "USD%2FJPY", label: "USDJPY", symbol: "OANDA:USDJPY" },
	{ value: "USD%2FCHF", label: "USDCHF", symbol: "OANDA:USDCHF" },
	{ value: "USD%2FCAD", label: "USDCAD", symbol: "OANDA:USDCAD" },
	{ value: "AUD%2FUSD", label: "AUDUSD", symbol: "OANDA:AUDUSD" },
	{ value: "NZD%2FUSD", label: "NZDUSD", symbol: "OANDA:NZDUSD" },
	{ value: "EUR%2FGBP", label: "EURGBP", symbol: "OANDA:EURGBP" },
	{ value: "EUR%2FJPY", label: "EURJPY", symbol: "OANDA:EURJPY" },
	{ value: "GBP%2FJPY", label: "GBPJPY", symbol: "OANDA:GBPJPY" },
	{ value: "EUR%2FCHF", label: "EURCHF", symbol: "OANDA:EURCHF" },
	{ value: "GBP%2FCHF", label: "GBPCHF", symbol: "OANDA:GBPCHF" },
	{ value: "AUD%2FJPY", label: "AUDJPY", symbol: "OANDA:AUDJPY" },
	{ value: "CAD%2FJPY", label: "CADJPY", symbol: "OANDA:CADJPY" },
	{ value: "AUD%2FNZD", label: "AUDNZD", symbol: "OANDA:AUDNZD" },
	{ value: "NZD%2FJPY", label: "NZDJPY", symbol: "OANDA:NZDJPY" },
	{ value: "GBP%2FAUD", label: "GBPAUD", symbol: "OANDA:GBPAUD" },
	{ value: "GBP%2FCAD", label: "GBPCAD", symbol: "OANDA:GBPCAD" },
	{ value: "GBP%2FNZD", label: "GBPNZD", symbol: "OANDA:GBPNZD" },
	{ value: "AUD%2FCAD", label: "AUDCAD", symbol: "OANDA:AUDCAD" },
	{ value: "AUD%2FCHF", label: "AUDCHF", symbol: "OANDA:AUDCHF" },
	{ value: "CAD%2FCHF", label: "CADCHF", symbol: "OANDA:CADCHF" },
	{ value: "CHF%2FJPY", label: "CHFJPY", symbol: "OANDA:CHFJPY" },
	{ value: "EUR%2FCAD", label: "EURCAD", symbol: "OANDA:EURCAD" },
	{ value: "NZD%2FCAD", label: "NZDCAD", symbol: "OANDA:NZDCAD" },
	{ value: "NZD%2FCHF", label: "NZDCHF", symbol: "OANDA:NZDCHF" },
	{ value: "SGD%2FJPY", label: "SGDJPY", symbol: "OANDA:SGDJPY" },
	{ value: "USD%2FSGD", label: "USDSGD", symbol: "OANDA:USDSGD" },
	{ value: "Gold%2FUSD", label: "XAUUSD", symbol: "OANDA:XAUUSD" },
	{ value: "Silver%2FUSD", label: "XAGUSD", symbol: "OANDA:XAGUSD" },
	//usoil
	{ value: "WTI%2FUSD", label: "USOIL", symbol: "TVC:USOIL" },
	//ukoil
	{ value: "Brent%2FUSD", label: "UKOIL", symbol: "TVC:UKOIL" },
];
