export const pairs = [
	{ value: "EUR%2FUSD", label: "EURUSD" },
	{ value: "GBP%2FUSD", label: "GBPUSD" },
	{ value: "USD%2FJPY", label: "USDJPY" },
	{ value: "USD%2FCHF", label: "USDCHF" },
	{ value: "USD%2FCAD", label: "USDCAD" },
	{ value: "AUD%2FUSD", label: "AUDUSD" },
	{ value: "NZD%2FUSD", label: "NZDUSD" },
	{ value: "EUR%2FGBP", label: "EURGBP" },
	{ value: "EUR%2FJPY", label: "EURJPY" },
	{ value: "GBP%2FJPY", label: "GBPJPY" },
	{ value: "EUR%2FCHF", label: "EURCHF" },
	{ value: "GBP%2FCHF", label: "GBPCHF" },
	{ value: "AUD%2FJPY", label: "AUDJPY" },
	{ value: "CAD%2FJPY", label: "CADJPY" },
	{ value: "AUD%2FNZD", label: "AUDNZD" },
	{ value: "NZD%2FJPY", label: "NZDJPY" },
	{ value: "GBP%2FAUD", label: "GBPAUD" },
	{ value: "GBP%2FCAD", label: "GBPCAD" },
	{ value: "GBP%2FNZD", label: "GBPNZD" },
	{ value: "AUD%2FCAD", label: "AUDCAD" },
	{ value: "AUD%2FCHF", label: "AUDCHF" },
	{ value: "CAD%2FCHF", label: "CADCHF" },
	{ value: "CHF%2FJPY", label: "CHFJPY" },
	{ value: "EUR%2FCAD", label: "EURCAD" },
	{ value: "NZD%2FCAD", label: "NZDCAD" },
	{ value: "NZD%2FCHF", label: "NZDCHF" },
	{ value: "SGD%2FJPY", label: "SGDJPY" },
	{ value: "USD%2FSGD", label: "USDSGD" },
	{ value: "Gold%2FUSD", label: "XAUUSD" },
	{ value: "Silver%2FUSD", label: "XAGUSD" },
	//usoil
	{ value: "WTI%2FUSD", label: "USOIL" },
	//ukoil
	{ value: "Brent%2FUSD", label: "UKOIL" },
];
